export default {
  FETCH_MEMBERS_REQUEST: "FETCH_MEMBERS_REQUEST",
  FETCH_MEMBERS_SUCCESS: "FETCH_MEMBERS_SUCCESS",
  FETCH_MEMBERS_FAILURE: "FETCH_MEMBERS_FAILURE",
  EDIT_MEMBER_REQUEST: "EDIT_MEMBER_REQUEST",
  EDIT_MEMBER_SUCCESS: "EDIT_MEMBER_SUCCESS",
  EDIT_MEMBER_FAILURE: "EDIT_MEMBER_FAILURE",
  CREATE_MEMBER_REQUEST: "CREATE_MEMBER_REQUEST",
  CREATE_MEMBER_SUCCESS: "CREATE_MEMBER_SUCCESS",
  CREATE_MEMBER_FAILURE: "CREATE_MEMBER_FAILURE",
  DELETE_MEMBER_REQUEST: "DELETE_MEMBER_REQUEST",
  DELETE_MEMBER_SUCCESS: "DELETE_MEMBER_SUCCESS",
  DELETE_MEMBER_FAILURE: "DELETE_MEMBER_FAILURE",
  JOIN_MEMBER_CHANNEL_SUCCESS: "JOIN_MEMBER_CHANNEL_SUCCESS",
  LEAVE_MEMBER_CHANNEL_SUCCESS: "LEAVE_MEMBER_CHANNEL_SUCCESS",
  HAS_NEW_MEMBER: "HAS_NEW_MEMBER",
  HAS_UPDATED_MEMBER: "HAS_UPDATED_MEMBER"
};
