export default {
  FETCH_MEMBERS_REQUEST: "FETCH_MEMBERS_REQUEST",
  FETCH_MEMBERS_SUCCESS: "FETCH_MEMBERS_SUCCESS",
  FETCH_MEMBERS_FAILURE: "FETCH_MEMBERS_FAILURE",
  JOIN_MEMBER_CHANNEL_SUCCESS: "JOIN_MEMBER_CHANNEL_SUCCESS",
  LEAVE_MEMBER_CHANNEL_SUCCESS: "LEAVE_MEMBER_CHANNEL_SUCCESS",
  HAS_NEW_MEMBER: "HAS_NEW_MEMBER"
};
