export default {
  FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
  SAVE_USER_REQUEST: "SAVE_USER_REQUEST",
  SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  SAVE_USER_FAILURE: "SAVE_USER_FAILURE",
  CONNECTED_TO_USER_CHANNEL: "CONNECTED_TO_USER_CHANNEL",
  HAS_NEW_USER: "HAS_NEW_USER"
};
